FROM node:slim


# install app dependencies
COPY ./client/package.json package.json
COPY ./client/package-lock.json package-lock.json

WORKDIR /client

RUN npm install --silent
RUN npm install react-scripts -g --silent

EXPOSE 3000

# start app
CMD ["npm", "run", "dev"]
