version: "3.4"
services:
  client:
    network_mode: host
    build:
      context: .
      target: video-service-client
  server:
    network_mode: host
    volumes: 
      - /root/video-service-free/videos:/root/videos
    build:
      context: .
      target: video-service-server
