services:
  server:
    container_name: dogehub_server
    image: dogehub_server
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: ./server/Dockerfile.server
    volumes:
      - ./server:/server

  client:
    container_name: dogehub_client
    image: dogehub_client
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: ./client/Dockerfile.client
    volumes:
      - ./client:/client
