version: "3.4"
services:
  client:
    network_mode: host
    build:
      context: .
      target: dogehub-client
  server:
    network_mode: host
    volumes: 
      - /root/dogehub/videos:/root/server/videos
    build:
      context: .
      target: dogehub-server
